[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
indicatif = "0.17.8"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
