[package]
name = "editor"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
engine = { path = "../engine" }
iced = { version = "0.13.1", features = ["advanced"] }
notify-rust = "4.11.3"
rfd = "0.15.0"
